### ISSUE TITLE
Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by frozenfung** [eniz/react-creditcard-input#3]
Hey, bro.
I appreciate that you make such a nice validator.
It really helps a lot when building our e-commerce system.

Just found a subtle issue here.
`Uncaught TypeError: Cannot read property 'type' of undefined`
It reminds me of this when I enter some number which can not be match with existed pattern.

I think we should check if `card` is undefined here.

**Comment by dphaener** [comment]
It also breaks the component. And it will not enforce the maximum length of 16 when it's a visa. You can just type numbers forever. I tried forking and hacking on it, but I can't get anything setup properly for development. I'll be redoing it from scratch and releasing it myself.

**Comment by frozenfung** [comment]
That would be great and I am looking forward to it :+1:

**Comment by dphaener** [comment]
@frozenfung I actually completely ditched it in favor of this: https://github.com/insin/react-maskedinput 

It's incredibly flexible, and if you want it to detect card types you can create a simple wrapper that will do that using the `CardTypes` file from this repo.
